
<!DOCTYPE html>
<html>
<head>
    <style>
    .center {
              display: block;
              margin-left: 125;
            }
    <title>Poster</title>
  </head>

<body>
    @foreach($post as $post)

    <h1 style="text-align: center; font-size: 28;"> Property Listing For: {{ $post->name }} </h1>
    <br/>
    <p style="font-size: 20;"> ADDRESS: {{ $post->address }} </p>
    <br/>
    <br/>

    <table>
        <tbody>

            <tr>
                <td>
                    <img src="data:image/png;base64, {!! base64_encode($img) !!}" width="350" height="350" class="center">
                </td>
            </tr>


        </tbody>

         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>
         <br/>

         <tfoot>
            <p>Generated by {{$site}}</p>
            <p>{{ $date }}</p>
        </tfoot>
    </table>

    @endforeach

</body>
</html>
